# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "12:6e:86:8a:9b:7c:cc:05:3c:5d:c6:c2:fb:8a:2e:ad"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn build
      - run: yarn compile
      - run: git config --global user.email "ci.circleci.com"
      - run: git config --global user.name "circleci_ci"
      - run: git add .
      - run: git commit -m 'circleci commit'
      - run: git push git@github.com:Ncnbb/well-cache.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master